
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'demo_pr'
version: '1.0.0'

vars:
  share_name: 'demo_pr_share'
  domain_database: 'demo_dr_db'
  schema: 'demo_pr'
  product_name: 'demo_pr'

# This setting configures which "profile" dbt uses for this project.
profile: 'demo_pr'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  demo_pr:
  
    staging:
      +materialized: table
    marts:
      +materialized: table
      tags: ["marts", var('product_name'), this]
      pre-hook: 
        - "{{create_share(var('share_name'), this)}}"
      post-hook: 
        - "{{list_product(var('schema'), this, var('share_name'))}}"
